-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 18:33:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webtrello
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webtrello` ;

-- -----------------------------------------------------
-- Schema webtrello
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webtrello` DEFAULT CHARACTER SET utf8 ;
USE `webtrello` ;

-- -----------------------------------------------------
-- Table `webtrello`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`usuario` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`quadro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`quadro` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`quadro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `cor_fundo` VARCHAR(45) NOT NULL,
  `cor_texto` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quadro_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_quadro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `webtrello`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`colecao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`colecao` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`colecao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_colecao_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_colecao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `webtrello`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`usuario_tem_quadro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`usuario_tem_quadro` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`usuario_tem_quadro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pode_editar` TINYINT(1) NOT NULL,
  `favorito` TINYINT(1) NOT NULL,
  `colecao_id` INT NULL,
  `usuario_id` INT NOT NULL,
  `quadro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tem_quadro_colecao1_idx` (`colecao_id` ASC) VISIBLE,
  INDEX `fk_usuario_tem_quadro_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_tem_quadro_quadro1_idx` (`quadro_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tem_quadro_colecao1`
    FOREIGN KEY (`colecao_id`)
    REFERENCES `webtrello`.`colecao` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_usuario_tem_quadro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `webtrello`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_tem_quadro_quadro1`
    FOREIGN KEY (`quadro_id`)
    REFERENCES `webtrello`.`quadro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`lista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`lista` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`lista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `quadro_id` INT NOT NULL,
  `ordem_lista` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lista_quadro1_idx` (`quadro_id` ASC) VISIBLE,
  CONSTRAINT `fk_lista_quadro1`
    FOREIGN KEY (`quadro_id`)
    REFERENCES `webtrello`.`quadro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`cartao` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` LONGTEXT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `lista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cartao_lista1_idx` (`lista_id` ASC) VISIBLE,
  CONSTRAINT `fk_cartao_lista1`
    FOREIGN KEY (`lista_id`)
    REFERENCES `webtrello`.`lista` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webtrello`.`documento_pdf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webtrello`.`documento_pdf` ;

CREATE TABLE IF NOT EXISTS `webtrello`.`documento_pdf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(200) NOT NULL,
  `cartao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documento_pdf_cartao1_idx` (`cartao_id` ASC) VISIBLE,
  CONSTRAINT `fk_documento_pdf_cartao1`
    FOREIGN KEY (`cartao_id`)
    REFERENCES `webtrello`.`cartao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
